# Docker Compose with Secrets Management for DeFiLlama
# Uses Docker secrets for sensitive data

version: '3.8'

secrets:
  # Database secrets
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_jwt_secret:
    file: ./secrets/postgres_jwt_secret.txt
  
  # API secrets
  anon_key:
    file: ./secrets/anon_key.txt
  service_role_key:
    file: ./secrets/service_role_key.txt
  
  # Auth secrets
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  smtp_password:
    file: ./secrets/smtp_password.txt
  
  # External API keys
  defillama_api_key:
    file: ./secrets/defillama_api_key.txt
  etherscan_api_key:
    file: ./secrets/etherscan_api_key.txt
  
  # Monitoring secrets
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt
  alertmanager_slack_webhook:
    file: ./secrets/alertmanager_slack_webhook.txt

services:
  # PostgreSQL with secrets
  db:
    image: supabase/postgres:15.1.0.117
    secrets:
      - postgres_password
      - postgres_jwt_secret
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_JWT_SECRET_FILE: /run/secrets/postgres_jwt_secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - defillama

  # Kong with secrets
  kong:
    image: kong:3.4.2
    secrets:
      - anon_key
      - service_role_key
    environment:
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PLUGINS: bundled,cors,key-auth,rate-limiting
    volumes:
      - ./supabase/kong.yml:/var/lib/kong/kong.yml:ro
    networks:
      - defillama

  # Auth service with secrets
  auth:
    image: supabase/gotrue:v2.99.0
    secrets:
      - jwt_secret
      - smtp_password
    environment:
      GOTRUE_JWT_SECRET_FILE: /run/secrets/jwt_secret
      GOTRUE_SMTP_PASS_FILE: /run/secrets/smtp_password
    networks:
      - defillama

  # Grafana with secrets
  grafana:
    image: grafana/grafana:10.2.2
    secrets:
      - grafana_admin_password
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - defillama

  # Alertmanager with secrets
  alertmanager:
    image: prom/alertmanager:v0.26.0
    secrets:
      - alertmanager_slack_webhook
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    networks:
      - defillama

networks:
  defillama:
    external: true

volumes:
  db-data:
  grafana-data:
  alertmanager-data:

