# Alertmanager Configuration for DeFiLlama Self-hosted Supabase
# Alert routing, grouping, and notification channels

global:
  # Resolve timeout
  resolve_timeout: 5m

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Alert routing tree
route:
  # Default receiver for all alerts
  receiver: 'default'
  
  # Group alerts by these labels
  group_by: ['alertname', 'severity', 'component']
  
  # Wait time before sending initial notification
  group_wait: 30s
  
  # Wait time before sending notification about new alerts in the same group
  group_interval: 5m
  
  # Wait time before re-sending notification for the same alert
  repeat_interval: 4h
  
  # Child routes for specific alert types (simplified for testing)
  routes:
    # All alerts go to default receiver for now
    - match_re:
        severity: '.*'
      receiver: 'default'

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress all alerts from an instance if the instance is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      instance: '.*'
    equal: ['instance']
  
  # Suppress high memory alerts if disk is full
  - source_match:
      alertname: 'DiskSpaceLow'
    target_match:
      alertname: 'HighMemoryUsage'
    equal: ['instance']
  
  # Suppress database connection alerts if database is down
  - source_match:
      alertname: 'PostgreSQLDown'
    target_match:
      alertname: 'PostgreSQLTooManyConnections'
    equal: ['instance']
  
  # Suppress Redis connection alerts if Redis is down
  - source_match:
      alertname: 'RedisDown'
    target_match:
      alertname: 'RedisHighConnectionCount'
    equal: ['instance']

# Notification receivers
receivers:
  # Default receiver (logs only)
  - name: 'default'
    # No webhook for now, just logs

