name: Premium E2E Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'premium/**'
      - '.github/workflows/premium-e2e-tests.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'premium/**'
      - '.github/workflows/premium-e2e-tests.yml'
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: defillama_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'premium/pnpm-lock.yaml'
      
      - name: Install pnpm
        run: npm install -g pnpm@latest
      
      - name: Install dependencies
        working-directory: premium
        run: pnpm install --frozen-lockfile
      
      - name: Verify PostgreSQL connection
        env:
          PGPASSWORD: test
        run: |
          psql -h localhost -U test -d defillama_test -c "SELECT version();"
      
      - name: Run E2E tests
        working-directory: premium
        env:
          TEST_DB: postgresql://test:test@localhost:5432/defillama_test
          NODE_ENV: test
        run: pnpm test:e2e
      
      - name: Upload E2E test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: premium/coverage/e2e/
          retention-days: 7
      
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: ./premium/coverage/e2e/lcov.info
          flags: e2e
          name: premium-e2e-coverage
          fail_ci_if_error: false
      
      - name: Comment PR with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testResults = `
            ## 🧪 E2E Test Results
            
            ✅ All E2E tests passed successfully!
            
            - **Test Suites:** 2 passed
            - **Tests:** 20 passed
            - **Duration:** ~12s
            
            ### Test Coverage
            - Whale Alert E2E: 9 tests ✅
            - Price Alert E2E: 11 tests ✅
            
            [View detailed results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: testResults
            });

